
global_costmap:
  footprint: [[-0.10, -0.225], [-0.10, 0.225], [0.10, 0.225], [0.10, -0.225]]
  footprint_padding: 0.02
  global_frame: map
  robot_base_frame: motion_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  width: 30
  height: 30
  transform_tolerance: 2.0

  inflation_layer: 
    enabled: true
    cost_scaling_factor: 2.58
    inflation_radius: 0.15
  # plugins:
  #   - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  # #   - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
