local_costmap:
  footprint: [[-0.1, -0.225], [-0.1, 0.225], [0.1, 0.225], [0.1, -0.225]]
  footprint_padding: 0.02
  global_frame: odom
  robot_base_frame: motion_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 2
  inflation_radius: 0.15
  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: mid360
    mid360: {
      data_type: PointCloud2,
      topic: /cloud_registered_body_1,
      marking: true,
      clearing: true,
      min_obstacle_height: -0.4,
      max_obstacle_height: 0.4
    }