image: /home/unitree/ws_loc/src/FAST_LIO_LOCALIZATION_HUMANOID/Navigation/config/map/map.pgm
resolution: 0.050000
origin: [-9.150439, -11.580884, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

